name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        feathersjs-version: [4, 5]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install npm@8
        if: matrix.node-version == '14.x'
        run: npm i -g npm@8
      - run: npm ci
      - name: install feathers packages for version ${{ matrix.feathersjs-version }}
        if: matrix.feathersjs-version == '4'
        run: npm i --no-save @feathersjs/feathers@^${{ matrix.feathersjs-version }} @feathersjs/express@^${{ matrix.feathersjs-version }}
      - run: npm test
        env:
          CI: true
